---
apiVersion: v1
kind: Namespace
metadata:
  name: diplom
  labels:
    name: diplom

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: diplom
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: sash39/nginx:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: diplom
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-apps
  namespace: diplom
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "http01-clusterissuer"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - nginx.kms-netology.ru
      secretName: domain-name-secret
  rules:
    - host: nginx.kms-netology.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nginx
                port:
                  number: 80

