name: Сборка Docker-образа

on:
  push:
    tags:
      - 'v*'
    branches:
      - '*'
env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
  my_build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Вход на Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.MY_TOKEN_DOCKER_HUB }}

      - name: Сборка Docker-образа
        run: |
          docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.USER_DOCKER_HUB }}/${{ env.IMAGE_NAME }}:latest
      - name: Push Docker-образа в Docker Hub
        run: |
          docker push ${{ secrets.USER_DOCKER_HUB }}/${{ env.IMAGE_NAME }}:latest
